spring:
  application:
    name: service-registry

server:
  port: 8761                    # Eureka port

eureka:
  instance:
    hostname: localhost         # Host name in Eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/