spring:
  application:
    name: zuul-api-gateway
server:
  port: 8080                    # Eureka instance port

eureka:
  instance:
    hostname: zuul-api-gateway         # Eureka instance host name
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

zuul:
  routes:
    ingest:
      path: /ingest/**
      url: http://localhost:9001/
      stripPrefix: true
    dashboard:
      path: /dashboard/**
      url: http://localhost:9004/
      stripPrefix: true