mongodb:
  image: mongo:latest
  container_name: "fitness-data-dashboard"
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    - AUTH=yes
    - MONGODB_APPLICATION_DATABASE=healthdata_db
  volumes:
    - ./data/db:/data/db
  ports:
    - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet